apiVersion: v1
kind: Service
metadata:
  name: mysql-client
  namespace: demo
  labels:
    app: mysql-client
spec:
  ports:
  - name: http
    port: 3306
  type: NodePort
  selector:
    app: mysql-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: demo
spec:
  selector:
    matchLabels:
      app: mysql-client
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-client
        version: v1
    spec:
      nodeSelector:
        enforcer: "true"
      containers:
      - image: quay.io/nvlab/mysql:8.0.22
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "1234567890"
